### ISSUE TITLE
Error: rba isn't supported any more, please use accounts.rba.setPolicy

### ISSUE THREAD

**Issue by mattsobo** [gigya/gigya-dev-toolkit#19]
When trying to copy settings from apikey to apikey

![image](https://cloud.githubusercontent.com/assets/17920691/22710297/695a3ce2-ed42-11e6-91e6-7e34d4e4cf66.png)

**Comment by scotthovestadt** [comment]
This is annoying because I think it's just calling getPolicy and then copying the response to setPolicy. I'll have to add a special exception to deal with that and do a few extra API calls. I'll look into a quick fix first to just not remove policies.rba and deal with adding it again via the extra API calls later.

**Comment by scotthovestadt** [comment]
Fixed.
